import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../src/scss/main.scss";
import ThemeRegistry from "@/src/components/theme-registry";
import AuthGuard from "@/src/components/client-guard";
import ContextWrapper from "@/src/context/ContextWrapper";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hello Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeRegistry>
          <AuthGuard>
            <ContextWrapper>
                {children}
            </ContextWrapper>
          </AuthGuard>
        </ThemeRegistry>
      </body>
    </html>
  );
}
