import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import "../src/scss/main.scss";
import ThemeRegistry from "@/src/components/theme-registry";
import ContextWrapper from "@/src/context/ContextWrapper";
import { AuthProvider } from "@/src/context/AuthContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shree Saraswati Secondary School",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <ThemeRegistry>
          <ContextWrapper>
            <AuthProvider>
              {children}
            </AuthProvider>
          </ContextWrapper>
        </ThemeRegistry>
      </body>
    </html>
  );
}
